[build]
  command = "pnpm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://xcevjnmdqthbnprywyyv.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZXZqbm1kcXRoYm5wcnl3eXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjY0OTgsImV4cCI6MjA1OTY0MjQ5OH0.JbEXstJn_vmJoDBSg3xMJN5TmR3ciSh1AoyAAqRiZpw"
  NODE_VERSION = "20"
  UPLOAD_DIR = "uploads"
  DEBUG = "true"
  LOGS_ACCESS_TOKEN = "6de3b4b6-8fcf-4a3a-9f7c-be55db65234e"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"

# Redirecionamentos e configurações de proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers específicos para tratar CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[dev]
  debug = true

# Configuração para lidar com uploads grandes
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true

[build.processing.images.resize]
  quality = 85

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[functions]
  node_bundler = "esbuild"
  included_files = ["uploads/**"]
  external_node_modules = ["@google/generative-ai"]

[functions.upload]
  included_files = ["uploads/**"] 