[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://xcevjnmdqthbnprywyyv.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjZXZqbm1kcXRoYm5wcnl3eXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjY0OTgsImV4cCI6MjA1OTY0MjQ5OH0.JbEXstJn_vmJoDBSg3xMJN5TmR3ciSh1AoyAAqRiZpw"
  NODE_VERSION = "20"
  UPLOAD_DIR = "uploads"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["uploads/**"]
  external_node_modules = ["@google/generative-ai"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 